org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

loader_version=0.19.3
loom_version=1.17-SNAPSHOT
moddev_version=2.0.144

minecraft_1_21_1_version=1.21.1
fabric_api_1_21_1_version=0.116.15+1.21.1
modmenu_1_21_1_version=11.0.3
neoforge_1_21_1_version=21.1.248

minecraft_26_2_version=26.2
fabric_api_26_2_version=0.154.2+26.2
modmenu_26_2_version=20.0.1
neoforge_26_2_version=26.2.0.63

maven_group=dev.neverket
archives_base_name=neverket-minimap
